chrome.runtime.onInstalled.addListener(()=>chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true}).catch(()=>{}));
chrome.runtime.onStartup.addListener(()=>chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true}).catch(()=>{}));
const getWorkflows=async()=>((await chrome.storage.local.get("workflows")).workflows||{}),getPending=async()=>((await chrome.storage.session.get("pending")).pending||{}),setPending=p=>chrome.storage.session.set({pending:p}),sitePattern=url=>{try{const u=new URL(url);return /^https?:$/.test(u.protocol)?`${u.origin}/*`:""}catch(e){return""}},siteName=url=>{try{return new URL(url).hostname}catch(e){return"this site"}};
async function hasSite(url){const p=sitePattern(url);return !!p&&chrome.permissions.contains({origins:[p]})}
async function queue(tabId,id){const p=await getPending();p[tabId]=id;await setPending(p)}
async function clearQueue(tabId){const p=await getPending();delete p[tabId];await setPending(p)}
async function ensureInjected(tabId){try{await chrome.tabs.sendMessage(tabId,{type:"ping"});return}catch(e){}await chrome.scripting.executeScript({target:{tabId},files:["content.js"]});await chrome.tabs.sendMessage(tabId,{type:"ping"})}
async function sendRun(tabId,id){const w=(await getWorkflows())[id];if(!w){await clearQueue(tabId);return}if(!await hasSite(w.url)){await clearQueue(tabId);return}try{await ensureInjected(tabId);await chrome.tabs.sendMessage(tabId,{type:"runWorkflow",workflow:w});await clearQueue(tabId)}catch(e){await clearQueue(tabId)}}
async function navigateAndRun(tabId,w,id){await queue(tabId,id);const t=await chrome.tabs.get(tabId);if(t.url===w.url)await chrome.tabs.reload(tabId);else await chrome.tabs.update(tabId,{url:w.url})}
chrome.tabs.onUpdated.addListener((tabId,info)=>{if(info.status!=="complete")return;getPending().then(p=>p[tabId]&&sendRun(tabId,p[tabId])).catch(()=>{})});
chrome.tabs.onRemoved.addListener(tabId=>clearQueue(tabId).catch(()=>{}));
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m.type!=="launchWorkflow")return;(async()=>{const w=(await getWorkflows())[m.id];if(!w)throw new Error("Workflow not found");if(!await hasSite(w.url))throw new Error(`WebRunner is not allowed on ${siteName(w.url)} yet.`);if(m.newTab){const t=await chrome.tabs.create({url:"about:blank",active:true});await queue(t.id,m.id);await chrome.tabs.update(t.id,{url:w.url});return reply({ok:true})}let tabId=s.tab?.id;if(!tabId){const[t]=await chrome.tabs.query({active:true,currentWindow:true});tabId=t?.id}if(!tabId)throw new Error("No browser tab available");await navigateAndRun(tabId,w,m.id);reply({ok:true})})().catch(e=>reply({ok:false,error:e.message}));return true});
